### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ajaysuwalka**
Corrected code snippet

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by ajaysuwalka** [comment]
@yahoocla done

**Comment by dreuxl** [comment]
Thanks @ajaysuwalka for that doc change, I ll merge it soon.

is that package useful for your projects?

**Comment by ajaysuwalka** [comment]
@dreuxl yes, but now I have implemented a new package which adds fit fdescribe based on our test rail case id. We don't want to run full specs for no reason.

**Pull request closed without merging**
